version: "3"

services:
  postgres:
    image: postgres:15
    container_name: postgresCatalizator
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalizator
    ports:
      - "5432:5432"